language: python
python: 
  - "3.6"
  - "nightly"
before_install: "pip install setuptools>38.5.1"
install: "pip install -r dev_requirements.txt"
before_script: "python setup.py install"
script: make test
